ALTER TABLE product_outputs
    ADD COLUMN remaining_quantity INT;

UPDATE product_outputs
SET remaining_quantity = quantity_produced
WHERE remaining_quantity IS NULL;

ALTER TABLE product_outputs
    ALTER COLUMN remaining_quantity SET NOT NULL;

CREATE TABLE product_output_allocations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id      BIGINT NOT NULL REFERENCES order_items (id),
    product_output_id  BIGINT REFERENCES product_outputs (id),
    quantity           INTEGER NOT NULL
);
