-- Baseline schema, replacing Hibernate's ddl-auto: update. Mirrors the JPA
-- entity mappings exactly as they exist today; every future schema change
-- goes into a new, versioned migration file instead.

CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    stock_quantity INTEGER NOT NULL,
    active         BOOLEAN NOT NULL
);

CREATE TABLE customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    address    VARCHAR(255) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE users (
    id            UUID PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name    VARCHAR(255) NOT NULL,
    last_name     VARCHAR(255) NOT NULL,
    street        VARCHAR(255) NOT NULL,
    postal_code   VARCHAR(255) NOT NULL,
    city          VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    enabled       BOOLEAN NOT NULL,
    created_at    TIMESTAMP
);

CREATE TABLE pack_options (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products (id),
    size       INTEGER NOT NULL,
    price      NUMERIC NOT NULL
);

CREATE TABLE customer_orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers (id),
    user_id     UUID REFERENCES users (id),
    status      VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP NOT NULL,
    total_price NUMERIC NOT NULL
);

CREATE TABLE order_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL REFERENCES customer_orders (id),
    product_id       BIGINT NOT NULL REFERENCES products (id),
    pack_size        INTEGER NOT NULL,
    pack_quantity    INTEGER NOT NULL,
    unit_pack_price  NUMERIC NOT NULL
);

CREATE TABLE account_tokens (
    id         UUID PRIMARY KEY,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    purpose    VARCHAR(255) NOT NULL,
    user_id    UUID NOT NULL REFERENCES users (id),
    expires_at TIMESTAMPTZ NOT NULL
);
