CREATE TABLE slot_availability (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_date          DATE NOT NULL,
    fulfillment_method VARCHAR(255) NOT NULL,
    slot               VARCHAR(255) NOT NULL,
    open               BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_slot_availability_date_method_slot UNIQUE (slot_date, fulfillment_method, slot)
);

CREATE TABLE fresh_batch_dates (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_date DATE NOT NULL UNIQUE,
    open       BOOLEAN NOT NULL DEFAULT TRUE
);

DROP TABLE fresh_availability;

ALTER TABLE customer_orders
    ADD COLUMN fulfillment_date DATE NOT NULL DEFAULT CURRENT_DATE;

ALTER TABLE customer_orders ALTER COLUMN fulfillment_date DROP DEFAULT;
