ALTER TABLE slot_availability DROP CONSTRAINT IF EXISTS uq_slot_availability_date_method_slot;
ALTER TABLE slot_availability DROP COLUMN slot;
ALTER TABLE slot_availability ADD COLUMN start_time TIME NOT NULL DEFAULT '00:00:00';
ALTER TABLE slot_availability ADD COLUMN end_time   TIME NOT NULL DEFAULT '00:00:00';
ALTER TABLE slot_availability ALTER COLUMN start_time DROP DEFAULT;
ALTER TABLE slot_availability ALTER COLUMN end_time DROP DEFAULT;

ALTER TABLE customer_orders DROP COLUMN slot;
ALTER TABLE customer_orders ADD COLUMN start_time TIME NOT NULL DEFAULT '00:00:00';
ALTER TABLE customer_orders ADD COLUMN end_time   TIME NOT NULL DEFAULT '00:00:00';
ALTER TABLE customer_orders ALTER COLUMN start_time DROP DEFAULT;
ALTER TABLE customer_orders ALTER COLUMN end_time DROP DEFAULT;

DROP TABLE fresh_batch_dates;

CREATE TABLE content_availability (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avail_date   DATE NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    open         BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_content_availability_date_type UNIQUE (avail_date, content_type)
);
