CREATE TABLE raw_materials (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    unit VARCHAR(255) NOT NULL
);

CREATE TABLE raw_material_purchases (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_material_id    BIGINT NOT NULL REFERENCES raw_materials (id),
    purchase_date      DATE NOT NULL,
    quantity_purchased NUMERIC NOT NULL,
    total_price_paid   NUMERIC NOT NULL,
    source             VARCHAR(255) NOT NULL
);
