CREATE TABLE production_sessions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_date DATE NOT NULL,
    notes        VARCHAR(2000)
);

CREATE TABLE raw_material_usages (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_session_id BIGINT NOT NULL REFERENCES production_sessions (id),
    raw_material_id        BIGINT NOT NULL REFERENCES raw_materials (id),
    quantity_used           NUMERIC NOT NULL
);

CREATE TABLE session_participants (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_session_id BIGINT NOT NULL REFERENCES production_sessions (id),
    user_id                 UUID NOT NULL REFERENCES users (id),
    hours_spent              NUMERIC NOT NULL
);

CREATE TABLE product_outputs (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_session_id BIGINT NOT NULL REFERENCES production_sessions (id),
    product_id               BIGINT NOT NULL REFERENCES products (id),
    quantity_produced         INTEGER NOT NULL
);
