package ch.celestin.gyoza.productionsession;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "production_sessions")
public class ProductionSession {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "session_date", nullable = false)
    private LocalDate date;

    // Lot/batch traceability code (e.g. "L20260825-01"), generated by the service layer
    // from the date and the day's session count — see ProductionSessionServiceImpl.
    @Column(name = "batch_number", nullable = false, unique = true)
    private String batchNumber;

    // Total time the whole session took, shared by every participant — not tracked per
    // participant since a session is worked together, not staggered.
    @Column(name = "duration_hours", nullable = false)
    private BigDecimal durationHours;

    private String notes;

    // Free-form additional costs (packaging, transport, ...) — 0 by default, editable after
    // creation via changeOtherCosts since these are often only known after the fact.
    @Column(name = "other_costs", nullable = false)
    private BigDecimal otherCosts;

    @OneToMany(
            mappedBy = "productionSession",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<RawMaterialUsage> rawMaterialUsages = new ArrayList<>();

    @OneToMany(
            mappedBy = "productionSession",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<SessionParticipant> participants = new ArrayList<>();

    @OneToMany(
            mappedBy = "productionSession",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<ProductOutput> outputs = new ArrayList<>();

    protected ProductionSession() {
    }

    public ProductionSession(
            LocalDate date,
            String batchNumber,
            BigDecimal durationHours,
            String notes,
            BigDecimal otherCosts
    ) {
        if (durationHours == null || durationHours.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException(
                    "La durée de la session doit être supérieure à 0"
            );
        }

        if (otherCosts != null && otherCosts.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException(
                    "Les autres charges ne peuvent pas être négatives"
            );
        }

        this.date = date;
        this.batchNumber = batchNumber;
        this.durationHours = durationHours;
        this.notes = notes;
        this.otherCosts = normalizeMoney(otherCosts != null ? otherCosts : BigDecimal.ZERO);
    }

    public void changeDetails(String notes, BigDecimal durationHours) {
        if (durationHours == null || durationHours.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException(
                    "La durée de la session doit être supérieure à 0"
            );
        }

        this.notes = notes;
        // Ensure at least one decimal so the field always serializes with a decimal point
        // ("5.0" rather than "5"), regardless of the scale the client sent.
        this.durationHours = durationHours.scale() < 1 ? durationHours.setScale(1) : durationHours;
    }

    public void changeOtherCosts(BigDecimal otherCosts) {
        if (otherCosts == null || otherCosts.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException(
                    "Les autres charges ne peuvent pas être négatives"
            );
        }

        this.otherCosts = normalizeMoney(otherCosts);
    }

    // Money fields are stored with a fixed scale so they always serialize with decimals
    // (e.g. "3.00" rather than "3"), regardless of the scale the client sent.
    private static BigDecimal normalizeMoney(BigDecimal value) {
        return value.setScale(2, RoundingMode.HALF_UP);
    }

    public void addRawMaterialUsage(RawMaterialUsage usage) {
        rawMaterialUsages.add(usage);
        usage.setProductionSession(this);
    }

    public void addParticipant(SessionParticipant participant) {
        participants.add(participant);
        participant.setProductionSession(this);
    }

    public void addOutput(ProductOutput output) {
        outputs.add(output);
        output.setProductionSession(this);
    }

    public Long getId() {
        return id;
    }

    public LocalDate getDate() {
        return date;
    }

    public String getBatchNumber() {
        return batchNumber;
    }

    public BigDecimal getDurationHours() {
        return durationHours;
    }

    public String getNotes() {
        return notes;
    }

    public BigDecimal getOtherCosts() {
        return otherCosts;
    }

    public List<RawMaterialUsage> getRawMaterialUsages() {
        return rawMaterialUsages;
    }

    public List<SessionParticipant> getParticipants() {
        return participants;
    }

    public List<ProductOutput> getOutputs() {
        return outputs;
    }
}
