package ch.celestin.gyoza.productionsession;

import jakarta.persistence.*;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "production_sessions")
public class ProductionSession {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "session_date", nullable = false)
    private LocalDate date;

    // Lot/batch traceability code (e.g. "L20260825-01"), generated by the service layer
    // from the date and the day's session count — see ProductionSessionServiceImpl.
    @Column(name = "batch_number", nullable = false, unique = true)
    private String batchNumber;

    private String notes;

    @OneToMany(
            mappedBy = "productionSession",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<RawMaterialUsage> rawMaterialUsages = new ArrayList<>();

    @OneToMany(
            mappedBy = "productionSession",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<SessionParticipant> participants = new ArrayList<>();

    @OneToMany(
            mappedBy = "productionSession",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<ProductOutput> outputs = new ArrayList<>();

    protected ProductionSession() {
    }

    public ProductionSession(LocalDate date, String batchNumber, String notes) {
        this.date = date;
        this.batchNumber = batchNumber;
        this.notes = notes;
    }

    public void addRawMaterialUsage(RawMaterialUsage usage) {
        rawMaterialUsages.add(usage);
        usage.setProductionSession(this);
    }

    public void addParticipant(SessionParticipant participant) {
        participants.add(participant);
        participant.setProductionSession(this);
    }

    public void addOutput(ProductOutput output) {
        outputs.add(output);
        output.setProductionSession(this);
    }

    public Long getId() {
        return id;
    }

    public LocalDate getDate() {
        return date;
    }

    public String getBatchNumber() {
        return batchNumber;
    }

    public String getNotes() {
        return notes;
    }

    public List<RawMaterialUsage> getRawMaterialUsages() {
        return rawMaterialUsages;
    }

    public List<SessionParticipant> getParticipants() {
        return participants;
    }

    public List<ProductOutput> getOutputs() {
        return outputs;
    }
}
